apiVersion: apps/v1
kind: Deployment
metadata:
  name: resttemplateserver
  labels:
    app: resttemplateserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resttemplateserver
  template:
    metadata:
      labels:
        app: resttemplateserver
   
    spec:
      containers:
        - name: resttemplateserver
          image: toomooroo/resttemplateserver
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/bookdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD    
              value: root1234
          
---
apiVersion: v1
kind: Service
metadata:
  name: resttemplateserver
spec:
  type: NodePort
  selector:
    app: resttemplateserver
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30102

